# Auto generated by ct-mksetup
# Do not edit this file, edit ./project.py instead

from setuptools import setup
setup(
    **{   'author': 'VIB/BEG/UGent',
    'author_email': 'timdiels.m@gmail.com',
    'classifiers': [   "'Intended Audience :: Science/Research',",
                       'Development Status :: 2 - Pre-Alpha',
                       'Environment :: Console',
                       'License :: OSI Approved',
                       'License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)',
                       'Natural Language :: English',
                       'Operating System :: POSIX',
                       'Operating System :: POSIX :: AIX',
                       'Operating System :: POSIX :: BSD',
                       'Operating System :: POSIX :: BSD :: BSD/OS',
                       'Operating System :: POSIX :: BSD :: FreeBSD',
                       'Operating System :: POSIX :: BSD :: NetBSD',
                       'Operating System :: POSIX :: BSD :: OpenBSD',
                       'Operating System :: POSIX :: GNU Hurd',
                       'Operating System :: POSIX :: HP-UX',
                       'Operating System :: POSIX :: IRIX',
                       'Operating System :: POSIX :: Linux',
                       'Operating System :: POSIX :: Other',
                       'Operating System :: POSIX :: SCO',
                       'Operating System :: POSIX :: SunOS/Solaris',
                       'Operating System :: Unix',
                       'Programming Language :: Python',
                       'Programming Language :: Python :: 3',
                       'Programming Language :: Python :: 3 :: Only',
                       'Programming Language :: Python :: 3.2',
                       'Programming Language :: Python :: 3.3',
                       'Programming Language :: Python :: 3.4',
                       'Programming Language :: Python :: 3.5',
                       'Programming Language :: Python :: Implementation',
                       'Programming Language :: Python :: Implementation :: CPython',
                       'Programming Language :: Python :: Implementation :: Stackless',
                       'Topic :: Scientific/Engineering',
                       'Topic :: Scientific/Engineering :: Artificial Intelligence',
                       'Topic :: Scientific/Engineering :: Bio-Informatics'],
    'description': 'Comparative co-expression network construction and visualization',
    'entry_points': {'console_scripts': ['coexpnetviz = deep_genome.coexpnetviz.main:main']},
    'extras_require': {   'dev': ['numpydoc', 'sphinx', 'sphinx-rtd-theme'],
                          'test': [   'coverage-pth',
                                      'pytest',
                                      'pytest-cov',
                                      'pytest-env',
                                      'pytest-mock',
                                      'pytest-xdist']},
    'install_requires': [   'attrs',
                            'chicken-turtle-util[sqlalchemy,data_frame,series,algorithms,configuration]',
                            'deep-genome-core',
                            'matplotlib'],
    'keywords': 'bioinformatics coexpression guilt-by-association',
    'license': 'LGPL3',
    'long_description': 'TODO\n'
                        '\n'
                        '.. Chicken Turtle Util (CTU) provides an API of various Python utility functions.\n'
                        '   \n'
                        '   Chicken Turtle Util is alpha. None of the interface is stable (yet), meaning it\n'
                        '   may change in the future.\n'
                        '   \n'
                        '   Chicken Turtle Util offers a variety of features, as such we kept most\n'
                        '   dependencies optional.  When using a module, add/install its dependencies,\n'
                        '   listed in its corresponding ``*_requirements.in`` file found in the root of the\n'
                        '   project; e.g.  `cli_requirements.in`__ lists the dependencies of\n'
                        '   `chicken_turtle_util.cli`.\n'
                        '\n'
                        '.. __: https://github.com/timdiels/chicken_turtle_util/blob/master/cli_requirements.in\n'
                        '\n'
                        'Links\n'
                        '=====\n'
                        '\n'
                        'TODO\n'
                        '\n'
                        '..\n'
                        '\n'
                        '   - `Documentation <http://pythonhosted.org/chicken_turtle_util/>`_\n'
                        '   - `PyPI <https://pypi.python.org/pypi/chicken_turtle_util/>`_\n'
                        '   - `GitHub <https://github.com/timdiels/chicken_turtle_util/>`_\n'
                        '\n'
                        'Features\n'
                        '========\n'
                        '\n'
                        'TODO\n'
                        '\n'
                        'Change log\n'
                        '==========\n'
                        '\n'
                        'v5.0.0\n'
                        '------\n'
                        '\n'
                        '- \n'
                        '- Added tests increasing coverage from 0% to TODO%\n'
                        '\n'
                        'Older versions\n'
                        '--------------\n'
                        'No change log\n',
    'name': 'deep-genome-coexpnetviz',
    'package_data': {   'deep_genome.coexpnetviz': [   'data/README.txt',
                                                       'data/coexpnetviz_style.xml',
                                                       'data/todo_cli.defaults.conf'],
                        'deep_genome.coexpnetviz.tests': [   'data/test_share_2_baits/Eggplant.txt',
                                                             'data/test_share_2_baits/Orth.txt',
                                                             'data/test_share_2_baits/TODO',
                                                             'data/test_share_2_baits/Tomato.txt',
                                                             'data/test_share_2_baits/baits.txt']},
    'packages': ['deep_genome', 'deep_genome.coexpnetviz', 'deep_genome.coexpnetviz.tests'],
    'url': 'https://gitlab.psb.ugent.be/deep_genome/coexpnetviz.git',
    'version': '0.0.0'}
)
