# Auto generated by ct-mksetup
# Do not edit this file, edit ./project.py instead

from setuptools import setup
setup(
    **{   'author': 'VIB/BEG/UGent',
    'author_email': 'timdiels.m@gmail.com',
    'classifiers': [   'Development Status :: 2 - Pre-Alpha',
                       "'Intended Audience :: Science/Research',",
                       'License :: OSI Approved',
                       'License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)',
                       'Natural Language :: English',
                       'Environment :: Console',
                       'Operating System :: POSIX',
                       'Operating System :: POSIX :: AIX',
                       'Operating System :: POSIX :: BSD',
                       'Operating System :: POSIX :: BSD :: BSD/OS',
                       'Operating System :: POSIX :: BSD :: FreeBSD',
                       'Operating System :: POSIX :: BSD :: NetBSD',
                       'Operating System :: POSIX :: BSD :: OpenBSD',
                       'Operating System :: POSIX :: GNU Hurd',
                       'Operating System :: POSIX :: HP-UX',
                       'Operating System :: POSIX :: IRIX',
                       'Operating System :: POSIX :: Linux',
                       'Operating System :: POSIX :: Other',
                       'Operating System :: POSIX :: SCO',
                       'Operating System :: POSIX :: SunOS/Solaris',
                       'Operating System :: Unix',
                       'Programming Language :: Python',
                       'Programming Language :: Python :: 3',
                       'Programming Language :: Python :: 3 :: Only',
                       'Programming Language :: Python :: 3.2',
                       'Programming Language :: Python :: 3.3',
                       'Programming Language :: Python :: 3.4',
                       'Programming Language :: Python :: 3.5',
                       'Programming Language :: Python :: Implementation',
                       'Programming Language :: Python :: Implementation :: CPython',
                       'Programming Language :: Python :: Implementation :: Stackless',
                       'Topic :: Scientific/Engineering',
                       'Topic :: Scientific/Engineering :: Bio-Informatics',
                       'Topic :: Scientific/Engineering :: Artificial Intelligence'],
    'description': 'Comparative co-expression network construction and visualization',
    'entry_points': {'console_scripts': ['coexpnetviz = deep_genome.coexpnetviz.main:main']},
    'extras_require': {   'dev': ['sphinx', 'numpydoc', 'sphinx-rtd-theme'],
                          'test': [   'pytest',
                                      'pytest-env',
                                      'pytest-xdist',
                                      'pytest-cov',
                                      'coverage-pth',
                                      'pytest-mock']},
    'install_requires': [   'chicken-turtle-util[sqlalchemy,data_frame,series,algorithms]',
                            'deep-genome-core',
                            'recordclass'],
    'keywords': 'bioinformatics coexpression guilt-by-association',
    'license': 'LGPL3',
    'long_description': 'TODO\n'
                        '\n'
                        'Links\n'
                        '=====\n'
                        '\n'
                        'TODO\n'
                        '\n'
                        'Features\n'
                        '========\n'
                        '\n'
                        'TODO\n'
                        '\n'
                        'Change log\n'
                        '==========\n'
                        '\n'
                        'v5.0.0\n'
                        '------\n'
                        '\n'
                        '-  \n'
                        '-  Added tests increasing coverage from 0% to TODO%\n'
                        '\n'
                        'Older versions\n'
                        '--------------\n'
                        '\n'
                        'No change log\n',
    'name': 'deep-genome-coexpnetviz',
    'package_data': {   'deep_genome.coexpnetviz': [   'data/README.txt',
                                                       'data/coexpnetviz_style.xml',
                                                       'data/todo_cli.defaults.conf'],
                        'deep_genome.coexpnetviz.tests': [   'data/test_share_2_baits/Eggplant.txt',
                                                             'data/test_share_2_baits/Orth.txt',
                                                             'data/test_share_2_baits/TODO',
                                                             'data/test_share_2_baits/Tomato.txt',
                                                             'data/test_share_2_baits/baits.txt']},
    'packages': ['deep_genome', 'deep_genome.coexpnetviz', 'deep_genome.coexpnetviz.tests'],
    'url': 'https://gitlab.psb.ugent.be/deep_genome/coexpnetviz.git',
    'version': '0.0.0'}
)
