# TODO update the production 'config' when finally done with all this

# Default Morph config
#
# Specifies which species are available for finding pathways identified by
# genes of interest in
cache_path: /tmp/morph  # Path to directory with read-write access for morph to use as cache
species_data_path: /mnt/midas/www/group/biocomp/extra/morph  # if provided, all paths are prefixed with this path

gene_collections:

    - name: Arabidopsis  # unique identifier (string)
      species: Arabidopsis
      example_goi: ['AT5G17230', 'AT4G14210', 'AT1G10830', 'AT3G04870', 'AT1G06820', 'AT3G10230', 'AT5G57030', 'AT4G25700', 'AT5G52570', 'AT1G31800', 'AT3G53130', 'AT5G67030', 'AT1G08550']  # Example GOI to show in GUIs as placeholder
      gene_web_page: 'http://www.arabidopsis.org/servlets/TairObject?name=$name&type=locus'  # url to page of gene, use $name as placeholder for the gene name
      gene_parser:  # description of how to parse genes of this collection into (gene-id, splice variant)
          # You can specify multiple match, replace (see rice below)
          - match: 'AT(.)G([0-9]{5})'  # Genes are part of the gene collection iff they match this regex pattern (perl syntax, case-insensitive). A suffix of numbers separated by dots is appended for you to this regex, where the last number is the splice variant; i.e. $your_matcher([.]$number)*[.]$splice_variant http://www.boost.org/doc/libs/1_57_0/libs/regex/doc/html/boost_regex/syntax/perl_syntax.html
            replace: 'AT$1G$2'  # As a gene is read into the database, it will be formatted by s/gene_format_match/gene_format_replace/ using boost-extended format string syntax. This results in just the gene name, no splice variant suffix. (http://www.boost.org/doc/libs/1_33_1/libs/regex/doc/format_boost_syntax.html)

    - name: 'Potato - ITAG'
      species: Potato
      example_goi: ['Sotub02g020720.1.1', 'Sotub02g020710.1.1', 'Sotub02g020130.1.1', 'Sotub07g023520.1.1', 'Sotub02g010840.1.1', 'Sotub11g008880.1.1', 'Sotub10g009720.1.1', 'Sotub05g026310.1.1', 'Sotub04g021880.1.1', 'Sotub07g025180.1.1', 'Sotub09g027860.1.1']
      gene_web_page: 'http://bioinformatics.psb.ugent.be/orcae/annotation/Soltu/current/$name'
      gene_parser:
          #TODO cut off the (. ... blabla) and splice_variant group, last number is the splice variant, anything after the dot gets stripped. And in the future we need to use a gene database like NCBI or something
          - match: 'Sotub([0-9]{2})g([0-9]{6})'
            replace: 'Sotub$1g$2'

    - name: 'Potato - PGSC'
      species: Potato
      example_goi: ['PGSC0003DMP400048099', 'PGSC0003DMP400033460', 'PGSC0003DMP400041818', 'PGSC0003DMP400023691', 'PGSC0003DMP400019953', 'PGSC0003DMP400039420', 'PGSC0003DMP400020813', 'PGSC0003DMP400027608', 'PGSC0003DMP400029983', 'PGSC0003DMP400010972', 'PGSC0003DMP400065555', 'PGSC0003DMP400023982', 'PGSC0003DMP400033908', 'PGSC0003DMP400020829']
      gene_web_page: 'http://potato.plantbiology.msu.edu/cgi-bin/annotation_report.cgi?gene_id=$name'
      gene_parser:
          - match: 'PGSC([0-9]{4})DMP([0-9]{9})'
            replace: 'PGSC$1DMP$2'

    - name: Tomato
      species: Tomato
      example_goi: ['Solyc10g084400', 'Solyc09g074850', 'Solyc09g011630', 'Solyc09g011540', 'Solyc09g011520', 'Solyc09g011510', 'Solyc09g007150', 'Solyc08g080910', 'Solyc08g080900', 'Solyc07g056500', 'Solyc07g056490', 'Solyc07g056480', 'Solyc07g056440', 'Solyc07g056420', 'Solyc06g009040', 'Solyc06g009020', 'Solyc05g006750', 'Solyc05g006740', 'Solyc02g081430', 'Solyc02g081340', 'Solyc02g068900', 'Solyc01g091330', 'Solyc01g086680', 'Solyc01g081310']
      gene_web_page: 'http://solgenomics.net/search/locus_search.pl?w8e4_any_name_matchtype=exactly&w8e4_any_name=$name&w8e4_common_name=&w8e4_phenotype=&w8e4_locus_linkage_group=&w8e4_ontology_term=&w8e4_editor=&w8e4_genbank_accession='
      gene_parser:
          - match: 'Solyc([0-9]{2})g([0-9]{6})'
            replace: 'Solyc$1g$2'

    - name: 'Rice - MSU'
      species: Rice
      #gene_web_page: TODO
      gene_parser:
          - match: 'LOC_Os([0-9]{2})g([0-9]{5})'
            replace: 'LOC_Os$1g$2'
          - match: '(.*)[.]fgenesh[.]mrna'
            replace: '$1.fgenesh.mrna'

    - name: 'Rice - RAP'
      species: Rice
      example_goi: ['Os01g0323600', 'Os01g0719100', 'LOC_Os01g01030']
      gene_web_page: 'http://rapdb.dna.affrc.go.jp/viewer/gbrowse_details/irgsp1?name=$name;feature_id=2503361'
      gene_parser:
          - match: 'Os([0-9]{2})g([0-9]{7})'
            replace: 'Os$1g$2'

    - name: 'Apple'
      species: Apple
      gene_parser:
          - match: 'MDP([0-9]{10})'
            replace: 'MDP$1'

# Functional annotations of genes
# Tab separated files mapping gene to gene-description. (You can put multiple gene collections in the same file)
functional_annotations:
    - ARABIDOBSIS/gene_descriptions  
    - ITAG/gene_descriptions
    - PGSC/gene_descriptions
    - TOMATO/gene_descriptions
    - rice/annotations

# (partial) 1-on-1 mappings between genes of two collections
# Tab separated files mapping gene to gene of other gene collection
# The inverse mapping is added automatically (i.e. the mapping is symmetric)
gene_mappings:
    - rice/msu_to_rap.mapping  

# TODO these names should be globally unique now
# All genes in an expression matrix have to be of the same gene collection
expression_matrices:
    # arabidopsis
    - name: 'Seed_GH'
      path: ARABIDOBSIS/data_sets/Seed_GH_DataSet.txt
      clusterings: # These clusterings are specific to the expression matrix
          - name: 'PPI matisse'
            path: ARABIDOBSIS/cluster_solution/Seed_GH_ppi_matisse_0.4.txt
          - name: 'CLICK'
            path: ARABIDOBSIS/cluster_solution/Seed_GH_CLICK_ClusteringSol.txt
          - name: 'IsEnzyme'
            path: ARABIDOBSIS/cluster_solution/Seed_GH_IsEnzymeClusteringSol.txt
    - name: 'Tissues'
      path: ARABIDOBSIS/data_sets/TissuesData.txt
      clusterings:
          - name: 'IsEnzyme'
            path: ARABIDOBSIS/cluster_solution/Tissues_IsEnzymeClusteringSol.txt
          - name: 'Metabolic matisse'
            path: ARABIDOBSIS/cluster_solution/Tissues_Metabolic_Network_ClusteringSol.txt
          - name: 'PPI matisse'
            path: ARABIDOBSIS/cluster_solution/Tissues_PPI_Network_ClusteringSol.txt
          - name: 'CLICK'
            path: ARABIDOBSIS/cluster_solution/Tissues_CLICK_ClusteringSol.txt
    - name: 'Seedlings'
      path: ARABIDOBSIS/data_sets/SeedlingsDataSet.txt
      clusterings:
          - name: 'IsEnzyme'
            path: ARABIDOBSIS/cluster_solution/Seedlings_IsEnzymeClusteringSol.txt
          - name: 'Metabolic matisse'
            path: ARABIDOBSIS/cluster_solution/Seedlings_Metabolic_Network_ClusteringSol.txt
          - name: 'PPI matisse'
            path: ARABIDOBSIS/cluster_solution/Seedlings_PPI_Network_ClusteringSol.txt
          - name: 'CLICK'
            path: ARABIDOBSIS/cluster_solution/Seedlings_CLICK_ClusteringSol.txt
    - name: 'abiotic_rma_TAIR10_v14'
      path: '/home/limyreth/doc/internship/CoExpNetViz/Data/cornet2.0/abiotic_rma_TAIR10_v14.txt'
    - name: 'biotic_rma_TAIR10_v14'
      path: '/home/limyreth/doc/internship/CoExpNetViz/Data/cornet2.0/biotic_rma_TAIR10_v14.txt'
    - name: 'stress_rma_TAIR10_v14'
      path: '/home/limyreth/doc/internship/CoExpNetViz/Data/cornet2.0/stress_rma_TAIR10_v14.txt'
    - name: 'atgenexpress_rma_TAIR10_v14'
      path: '/home/limyreth/doc/internship/CoExpNetViz/Data/cornet2.0/atgenexpress_rma_TAIR10_v14.txt'
    - name: 'compendium_15_rma_TAIR10_v14'
      path: '/home/limyreth/doc/internship/CoExpNetViz/Data/cornet2.0/compendium_15_rma_TAIR10_v14.txt'

    # Potato ITAG
    - name: 'All tissues'
      path: ITAG/data_sets/All_TissuesDataSet_ITAG.txt	
      clusterings:
          - name: 'IsEnzyme'
            path: ITAG/cluster_solution/IsEnzyme_ClusteringSol_ITAG.txt
          - name: 'Metabolic matisse'
            path: ITAG/cluster_solution/Metabolic Network_ClusteringSol_All_Tissues_ITAG.txt
          - name: 'PPI matisse'
            path: ITAG/cluster_solution/PPI_Network_ClusteringSol_All_Tissues_ITAG.txt
          - name: 'CLICK'
            path: ITAG/cluster_solution/ITAG_CLICK_ClusteringSol.txt
    - name: 'Leafs'
      path: ITAG/data_sets/Leafs_ITAG.txt	
      clusterings:
          - name: 'IsEnzyme'
            path: ITAG/cluster_solution/IsEnzyme_ClusteringSol_ITAG.txt
          - name: 'Metabolic matisse'
            path: ITAG/cluster_solution/Metabolic Network_ClusteringSol_Leafs_ITAG.txt
          - name: 'PPI matisse'
            path: ITAG/cluster_solution/PPI_Network_ClusteringSol_Leafs_ITAG.txt
          - name: 'CLICK'
            path: ITAG/cluster_solution/ITAG_leafs_CLICK_ClusteringSol.txt
    - name: 'Roots'
      path: ITAG/data_sets/Root_ITAG.txt	
      clusterings:
          - name: 'IsEnzyme'
            path: ITAG/cluster_solution/IsEnzyme_ClusteringSol_ITAG.txt
          - name: 'Metabolic matisse'
            path: ITAG/cluster_solution/Metabolic Network_ClusteringSol_Roots_ITAG.txt
          - name: 'PPI matisse'
            path: ITAG/cluster_solution/PPI_Network_ClusteringSol_Roots_ITAG.txt
          - name: 'CLICK'
            path: ITAG/cluster_solution/ITAG_roots_CLICK_ClusteringSol.txt
    - name: 'Tuber'
      path: ITAG/data_sets/Tuber_ITAG.txt	
      clusterings:
          - name: 'IsEnzyme'
            path: ITAG/cluster_solution/IsEnzyme_ClusteringSol_ITAG.txt
          - name: 'Metabolic matisse'
            path: ITAG/cluster_solution/Metabolic Network_ClusteringSol_Tuber_ITAG.txt
          - name: 'PPI matisse'
            path: ITAG/cluster_solution/PPI_Network_ClusteringSol_Tuber_ITAG.txt
          - name: 'CLICK'
            path: ITAG/cluster_solution/ITAG_tuber_CLICK_ClusteringSol.txt

    # Potato PGSC
    - name: 'All tissues'
      path: PGSC/data_sets/All_TissuesDataSet_PGSC.txt
      clusterings:
          - name: 'IsEnzyme'
            path: PGSC/cluster_solution/IsEnzyme_ClusteringSol.txt
          - name: 'Metabolic matisse'
            path: PGSC/cluster_solution/Metabolic Network_clusteringSol_All_Tissues_PGSC.txt
          - name: 'PPI matisse'
            path: PGSC/cluster_solution/PPI_Network_ClusteringSol_All_Tissues_PGSC.txt
          - name: 'CLICK'
            path: PGSC/cluster_solution/PGSC_CLICK_ClusteringSol.txt
    - name: 'Leafs'
      path: PGSC/data_sets/LeafsDataSet_PGSC.txt
      clusterings:
          - name: 'IsEnzyme'
            path: PGSC/cluster_solution/IsEnzyme_ClusteringSol.txt
          - name: 'Metabolic matisse'
            path: PGSC/cluster_solution/Metabolic Network_clusteringSol_Leafs_PGSC.txt
          - name: 'PPI matisse'
            path: PGSC/cluster_solution/PPI_Network_ClusteringSol_Leafs_PGSC.txt
          - name: 'CLICK'
            path: PGSC/cluster_solution/PGSC_leafs_CLICK_ClusteringSol.txt
    - name: 'Roots'
      path: PGSC/data_sets/RootsDataSet_PGSC.txt
      clusterings:
          - name: 'IsEnzyme'
            path: PGSC/cluster_solution/IsEnzyme_ClusteringSol.txt
          - name: 'Metabolic matisse'
            path: PGSC/cluster_solution/Metabolic Network_clusteringSol_Roots_PGSC.txt
          - name: 'PPI matisse'
            path: PGSC/cluster_solution/PPI_Network_ClusteringSol_Roots_PGSC.txt
          - name: 'CLICK'
            path: PGSC/cluster_solution/PGSC_roots_CLICK_ClusteringSol.txt
    - name: 'Tuber'
      path: PGSC/data_sets/Tuber_PGSC.txt
      clusterings:
          - name: 'IsEnzyme'
            path: PGSC/cluster_solution/IsEnzyme_ClusteringSol.txt
          - name: 'Metabolic matisse'
            path: PGSC/cluster_solution/Metabolic Network_clusteringSol_Tuber_PGSC.txt
          - name: 'PPI matisse'
            path: PGSC/cluster_solution/PPI_Network_ClusteringSol_Tuber_PGSC.txt
          - name: 'CLICK'
            path: PGSC/cluster_solution/PGSC_tuber_CLICK_ClusteringSol.txt
    # Tomato
    - name: 'Root and leaf'
      path: TOMATO/data_sets/RootAndLeafDataSet.txt
      clusterings:
          - name: 'IsEnzyme'
            path: TOMATO/cluster_solution/IsEnzymeTomatoClusteringSol.txt
          - name: 'Metabolic matisse'
            path: TOMATO/cluster_solution/RootAndLeaf_MetabolicNetworkClusteringSol.txt
          - name: 'Null clustering'
            path: TOMATO/cluster_solution/nullClusteringSol.txt
          - name: 'PPI matisse'
            path: TOMATO/cluster_solution/RootAndLeaf_PPI_Network_ClusteringSol.txt
          - name: 'MCL'
            path: TOMATO/cluster_solution/RootAndLeaf_MCL_ClusteringSol.txt
          - name: 'CLICK'
            path: TOMATO/cluster_solution/RootAndLeaf_CLICK_clusteringSol.txt
    - name: 'Fruit'
      path: TOMATO/data_sets/FruitDataSet.txt
      clusterings:
          - name: 'IsEnzyme'
            path: TOMATO/cluster_solution/IsEnzymeTomatoClusteringSol.txt
          - name: 'Metabolic matisse'
            path: TOMATO/cluster_solution/Fruit_MetabolicNetworkClusteringSol.txt
          - name: 'Null clustering'
            path: TOMATO/cluster_solution/nullClusteringSol.txt
          - name: 'PPI matisse'
            path: TOMATO/cluster_solution/Fruit_PPI_Network_ClusteringSo.txt
          - name: 'MCL'
            path: TOMATO/cluster_solution/Fruit_MCL_ClusteringSol.txt
          - name: 'CLICK'
            path: TOMATO/cluster_solution/Fruit_CLICK_clusteringSol.txt

    # Rice: MSU and RAP
    - name: 'E-GEOD-14275'
      path: 'rice/data_sets/E-GEOD-14275.expression_matrix'
      clusterings:
          - name: 'PPI matisse'
            path: 'rice/clusterings/E-GEOD-14275_ppi_mcl_matisse.clustering'
          - name: 'CLICK'
            path: 'rice/clusterings/E-GEOD-14275_click.clustering'
          - name: 'IsEnzyme'
            path: 'rice/clusterings/is_enzyme.clustering'
    - name: 'E-GEOD-25073'
      path: 'rice/data_sets/E-GEOD-25073.expression_matrix'
      clusterings:
          - name: 'PPI matisse'
            path: 'rice/clusterings/E-GEOD-25073_ppi_mcl_matisse.clustering'
          - name: 'CLICK'
            path: 'rice/clusterings/E-GEOD-25073_click.clustering'
          - name: 'IsEnzyme'
            path: 'rice/clusterings/is_enzyme.clustering'
    - name: 'E-GEOD-31077'
      path: 'rice/data_sets/E-GEOD-31077.expression_matrix'
      clusterings:
          - name: 'PPI matisse'
            path: 'rice/clusterings/E-GEOD-31077_ppi_mcl_matisse.clustering'
          - name: 'CLICK'
            path: 'rice/clusterings/E-GEOD-31077_click.clustering'
          - name: 'IsEnzyme'
            path: 'rice/clusterings/is_enzyme.clustering'
    - name: 'E-GEOD-35984'
      path: 'rice/data_sets/E-GEOD-35984.expression_matrix'
      clusterings:
          - name: 'PPI matisse'
            path: 'rice/clusterings/E-GEOD-35984_ppi_mcl_matisse.clustering'
          - name: 'CLICK'
            path: 'rice/clusterings/E-GEOD-35984_click.clustering'
          - name: 'IsEnzyme'
            path: 'rice/clusterings/is_enzyme.clustering'
    - name: 'E-GEOD-39298'
      path: 'rice/data_sets/E-GEOD-39298.expression_matrix'
      clusterings:
          - name: 'PPI matisse'
            path: 'rice/clusterings/E-GEOD-39298_ppi_mcl_matisse.clustering'
          - name: 'CLICK'
            path: 'rice/clusterings/E-GEOD-39298_click.clustering'
          - name: 'IsEnzyme'
            path: 'rice/clusterings/is_enzyme.clustering'
    - name: 'E-GEOD-5167'
      path: 'rice/data_sets/E-GEOD-5167.expression_matrix'
      clusterings:
          - name: 'PPI matisse'
            path: 'rice/clusterings/E-GEOD-5167_ppi_mcl_matisse.clustering'
          - name: 'CLICK'
            path: 'rice/clusterings/E-GEOD-5167_click.clustering'
          - name: 'IsEnzyme'
            path: 'rice/clusterings/is_enzyme.clustering'
    - name: 'E-GEOD-8216'
      path: 'rice/data_sets/E-GEOD-8216.expression_matrix'
      clusterings:
          - name: 'PPI matisse'
            path: 'rice/clusterings/E-GEOD-8216_ppi_mcl_matisse.clustering'
          - name: 'CLICK'
            path: 'rice/clusterings/E-GEOD-8216_click.clustering'
          - name: 'IsEnzyme'
            path: 'rice/clusterings/is_enzyme.clustering'
    - name: 'E-MEXP-2267'
      path: 'rice/data_sets/E-MEXP-2267.expression_matrix'
      clusterings:
          - name: 'PPI matisse'
            path: 'rice/clusterings/E-MEXP-2267_ppi_mcl_matisse.clustering'
          - name: 'CLICK'
            path: 'rice/clusterings/E-MEXP-2267_click.clustering'
          - name: 'IsEnzyme'
            path: 'rice/clusterings/is_enzyme.clustering'
                #TODO all these other clusterings
    - name: 'RiceGenomeDataSet'
      path: 'rice/data_sets/RiceGenomeDataSet.expression_matrix'

# Clusterings
# All genes in a clustering have to be of the same gene collection
# Some clusterings can only be used with a particular expression matrix, others are global
# Duplicate names are sometimes allowed. To be specific, (name, expression matrix, gene collection) tuple has to be unique.
clusterings:
    - name: 'Rice: PPI matisse'
      path: 'rice/clusterings/RiceGenomeDataSet_ppi_mcl_matisse.clustering'

    - name: 'Rice: CLICK'
      path: 'rice/clusterings/RiceGenomeDataSet_click.clustering'

    - name: 'Rice: IsEnzyme'
      path: 'rice/clusterings/is_enzyme.clustering'

# Orthologs
# Plain text files where each line is a group of orthologs.
# You're allowed to specify a gene on multiple lines, as long as the corresponding groups are equal (same set of genes)
orthologs:
    - name: 'Plaza Monocot'
      path: '/mnt/midas/group/biocomp/projects/morph/coexpr/data/plaza_source/orthologs_monocot'
    - name: 'Plaza Dicot'
      path: '/mnt/midas/group/biocomp/projects/morph/coexpr/data/plaza_source/orthologs_dicot'
    - name: 'PGSC - ITAG mapping'
      path: '/mnt/midas/group/biocomp/projects/morph/coexpr/data/pgsc_itag/orthologs'
