# Conda recipe
{% set data = load_setup_py_data() %}

package:
  name: coexpnetviz
  version: '{{ data['version'] }}'

source:
  path: ..

build:
  script: '{{ PYTHON }} -m pip install . -vv'
  entry_points:
    - coexpnetviz = coexpnetviz.main:main

requirements:
  build:
    - pip
    - python
  host:
    # Conda recommends always adding the interpreter as a host dep
    - python
  run:
    - python
    - attrs
    - matplotlib
    - numpy
    - pandas
    - more-itertools
    - varbio ==3.*

test:
  source_files:
    - pytest.ini
    - tests
  requires:
    - pytest >=3
    - pytil ==8.*
  commands:
    - pytest -l --tb=auto

about:
  home: https://github.com/CoExpNetViz/coexpnetviz-python
  license: LGPL3
  license_file: LICENSE.txt
  summary: Internal python CLI used by CoExpNetViz Cytoscape app
