'''
TODO short description, ref to project site, to doc, ...
'''

from deep_genome.coexpnetviz._various import Network, NodeType, RGB
from deep_genome.coexpnetviz._algorithm import create_network
from deep_genome.coexpnetviz._cytoscape_writer import write_cytoscape

def initialise():
    '''
    Must be called before using deep_genome.coexpnetviz
    
    Any calls but the first are ignored
    '''
    from deep_genome import core
    core.initialise()

__version__ = '0.0.0'  # Auto generated by ct-mksetup, do not edit this line. Project version is only set nonzero on release, using `ct-release`.