# Analog to pytil's workflow
name: Publish to anaconda

on: [push]

jobs:
  publish-conda-pkg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1.1.0
      with:
        activate-conda: false
        python-version: 3.8.*
    - name: Install conda tools
      run: conda install -y anaconda-client conda-build
    - name: Build conda pkg
      run: |
        mkdir dist
        conda build . --channel anaconda --channel timdiels --output-folder dist
#   - name: Publish to anaconda
#     run: anaconda upload --all dist/linux-64/*.tar.bz2
#     env:
#       ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
