# Analog to pytil's workflow
name: Publish to anaconda

on: [push]

jobs:
  publish-conda-pkg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: latest
        python-version: 3.8.*
        auto-update-conda: true
        conda-build-version: 3.*
    - name: Install anaconda uploader
      shell: bash -l {0}
      run: conda install -y anaconda-client
   - name: Publish to anaconda
     shell: bash -l {0}
     run: $CONDA_PREFIX/bin/anaconda #upload --all dist/linux-64/*.tar.bz2
     env:
       ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
    - name: Build conda pkg
      shell: bash -l {0}
      run: |
        mkdir dist
        conda build . --channel anaconda --channel timdiels --output-folder dist
